### ISSUE TITLE
AWS Region needs to be specified

### ISSUE THREAD

**Issue by picsoung** [obie/saws#1]
Hi,

Just discovered this tool. I am planning to use it with Serverless framework.

Just ran my first command and I noticied one thing:
you have to specify the AWS region to make your example work on Serverless
for example
`AWS.config.update({region:'us-east-1'});`

Otherwise you get an error 
```
Serverless: -----------------
Serverless: Failed - This Error Was Thrown:
Serverless: RangeError: Maximum call stack size exceeded
```
Maybe it worth mentioning on the README :)
Thanks

**Comment by obie** [comment]
Added a note to the README. Thanks!
